# Generated by Django 5.2.7 on 2025-11-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproduto',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to='estoque_app.produto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Mov_entrada',
        ),
    ]
