# Generated by Django 5.2.7 on 2025-12-02 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_app', '0002_entradaproduto_produto_delete_mov_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaproduto',
            name='produto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='mov_saidas', to='estoque_app.produto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Mov_saida',
        ),
    ]
